name: grinlintsa
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  path_provider: ^2.1.2
  dart_date: ^1.3.2
  numberpicker: ^2.1.2
  blue_thermal_printer: ^1.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logorussie.png
    - assets/background.jpg
    - assets/icon-legumes.png
    - assets/icon-pizza.png
    - assets/icon-shawarma.png
    - assets/icon-sushi.png
    - assets/bg-legumes.jpg
    - assets/bg-pizza.jpg
    - assets/bg-shawarma.jpg
    - assets/bg-sushi.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logorussie.png"
